# Configuración de análisis SonarQube.
sonar.projectKey=agrotech-t-backend
sonar.projectName=AGROTECH-T_Backend
sonar.sources=apps,common,config
sonar.tests=apps/accounts/tests
sonar.test.inclusions=apps/accounts/tests/**/*.py
sonar.exclusions=apps/accounts/migrations/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=manage.py,config/asgi.py,config/wsgi.py
sonar.qualitygate.wait=true
